### ISSUE TITLE
how to visualize the log amplitudes

### ISSUE THREAD

**Issue by iendi** [NVlabs/T-Stitch#1]
Thank you for sharing this exciting work!  
I would like to know if you could share the code to visualize the log amplitudes as shown in your papers

**Comment by HubHop** [comment]
Hi @iendi, thanks for your interests! Please find the code [here](https://github.com/NVlabs/T-Stitch/blob/main/dit/visualize_sampling_freq.py).

**Comment by iendi** [comment]
Thanks for reply! I will try it.
