### ISSUE TITLE
How many steps do you train for DiT-S and DiT-B?

### ISSUE THREAD

**Issue by wangbo-zhao** [NVlabs/T-Stitch#3]
How many steps do you train for DiT-S and DiT-B? Thanks.

**Comment by HubHop** [comment]
Hi @wangbo-zhao, thanks for your interest! The details of the two models are provided in our appendix Table 3. DiT-S is trained for 5000K steps and DiT-B is trained for 1600K steps. There is also a study on the effect of different DiT-S checkpoints in Figure 18.

<img width="1240" alt="image" src="https://github.com/NVlabs/T-Stitch/assets/20661773/85a069bf-e6d2-4dab-87d9-2215150f4933">

<img width="1203" alt="image" src="https://github.com/NVlabs/T-Stitch/assets/20661773/a2449803-1f58-4d46-a439-5a4635d32245">

**Comment by wangbo-zhao** [comment]
Got it. Thanks!
